# Inclure la config de base ModSecurity
Include /etc/nginx/modsecurity/modsecurity.conf

#  moteur (On = bloque, DetectionOnly = log seulement)
SecRuleEngine On 

#  permet de voir dans les logs ce que ModSecurity aurait bloqué, sans risquer de casser WordPress pendant tes tests. Une fois que tout est stable tu passes à On
SecRuleEngine On

#core rule
Include /etc/nginx/modsecurity/crs/crs-setup.conf
Include /etc/nginx/modsecurity/crs/rules/*.conf

# Logs d'audit
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogFormat JSON
SecAuditLogParts ABCFHZ