global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_by:
    - alertname
    - cluster
    - service
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: discord
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1504048704858886164/avtz1GDlMEVfQ2UE1ULxXTUfLtx7hmkOJbW8xtMPOEe1KybQAo9UAYRBfuVH31l6XVgA
        send_resolved: true
