
filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - dissect:
          tokenizer: "/var/lib/docker/containers/%{container_id}/%{filename}"
          field: "log.file.path"
          target_prefix: ""
      - add_fields:
          target: ''
          fields:
            service_name: "${container_id}"

output.logstash:
  hosts: ["logstash:5044"]

# Pour debug (optionnel)
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
