# Exclusions pour les routes d'upload cette URL spécifique, désactive toutes les règles
SecRule REQUEST_URI "@beginsWith /api/users/upload-avatar" \
    "id:1000,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"