input {
  beats {
    host => "0.0.0.0"
    port => 5044
  }
}

filter {
  if ![event][dataset] {
    mutate {
      add_field => { "[event][dataset]" => "transcendence.logs" }
    }
  }

  if [container][name] {
    mutate {
      copy => { "[container][name]" => "container_name" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTIC_HOSTS}"]
    user => "${ELASTIC_USERNAME}"
    password => "${ELASTIC_PASSWORD}"
    ilm_enabled => true
    ilm_rollover_alias => "transcendence-logs"
    ilm_pattern => "000001"
    ilm_policy => "transcendence-logs-policy"
    manage_template => false
  }
}
